# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

gt-0.50-0.30-0.30:
  clustering:
    geotemporal:
      reducer:
        lambda_ts: 0.50
        node_threshold: 0.30
        day_threshold: 0.30
        pca_days:
          enable: false

gt-0.75-0.28-0.22-True:
  clustering:
    geotemporal:
      reducer:
        lambda_ts: 0.75
        node_threshold: 0.28
        day_threshold: 0.22
        pca_days:
          enable: true

gt-0.25-0.22-0.38:
  clustering:
    geotemporal:
      reducer:
        lambda_ts: 0.25
        node_threshold: 0.22
        day_threshold: 0.38
        pca_days:
          enable: false

gt-0.50-0.40-0.40-True:
  clustering:
    geotemporal:
      reducer:
        lambda_ts: 0.50
        node_threshold: 0.40
        day_threshold: 0.40
        pca_days:
          enable: true
